apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litmus-agent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/litmuschaos/litmus-helm.git
    targetRevision: litmus-agent-3.11.2
    path: charts/litmus-agent
    helm:
      releaseName: litmus-agent
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: litmus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
