apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: litmus-agent
  namespace: argocd  # Or the namespace where your ArgoCD instance is installed
spec:
  project: default
  source:
    repoURL: https://litmuschaos.github.io/litmus-helm/
    chart: litmus-agent
    targetRevision: 3.6.0  # Use the desired version
    helm:
      releaseName: litmus-agent
      values: |
        agent:
          mode: cluster
          nodeSelector: {}
          tolerations: []
        global:
          namespace: litmus
  destination:
    server: https://kubernetes.default.svc
    namespace: litmus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
