apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.infraConfigName }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookFailed
data: {}